### ISSUE TITLE
A simple improvement

### ISSUE THREAD

**Issue by r4nm4** [Icehunter/ffxivapp-plugin-log#5]
Dear Ryan,
first of all, thank you so much for this amazing plugin.
I'm wondering if can I ask you a little and simple improvement inside your plugin.

Is it possible log in realtime inside 1 file... exactly all what we see "Plugin -> Log -> All" screen?
In my opinion could be great have a history about our chat and very simple to read.

Please please let me know.
Thank you.

**Comment by Icehunter** [comment]
It actually does but not in a txt file currently. It's in an XML log called ChatHistory.xml Under My Docs\FFXIVAPP\Logs\DateTime_ChatHistory.xml

If you want to view without opening the app I have this project which can do so:

https://github.com/Icehunter/ffxivapp-chatlog-importer

**Comment by r4nm4** [comment]
Thanks
