### ISSUE TITLE
Request: Translation Window

### ISSUE THREAD

**Issue by Mhitra** [Icehunter/ffxivapp-plugin-log#6]
Dear Ryan,
thank you again for you amazing app ;)
Could I try to ask you a little improve?
Could you add a simple window (like DPS parser) with the output of the translation?
Should be awesome can read from chat what JP ppl write in a window.
Thank you

**Comment by r4nm4** [comment]
Please Ryan...

**Comment by Mashrien** [comment]
I've already created something like this (but with several additional features) for personal use.. If Ice gets this thing updated for 4.0, I'll push my code to Git from my personal repos for others to use.

**Comment by Mhitra** [comment]
LOL... I did that looong time ago :p

**Comment by Icehunter** [comment]
@Mhitra Sorry ^^; New job, baby and not playing game. I'll do my best.

**Comment by Mhitra** [comment]
Oh @Icehunter please you don't need to say something :)))
You did an amazing job!!! And really thank you.
Of course... life >>>> game :) No apologies.
All the best!

**Comment by Icehunter** [comment]
![image](https://user-images.githubusercontent.com/677341/27771704-10dac29c-5f09-11e7-8b1a-20fa1c7d4431.png)

**Comment by Icehunter** [comment]
Pushing this out today.
